---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  Name:
    Type: String
  FullyQualifiedDomainName:
    Type: String
  CertificateArn:
    Type: String
  BucketName:
    Type: String
  BucketArn:
    Type: String
  BucketRegionalFqdn:
    Type: String
  CloudFrontPriceClass:
    Type: String
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All


Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref Name

  
  OriginAccessPermissions:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub ${BucketArn}/*
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId

  SecurityHeaders:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub ${Name}-SecurityHeaders
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            ContentSecurityPolicy: default-src 'self'; upgrade-insecure-requests
            Override: True
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Preload: true
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true
        CustomHeadersConfig:
          Items:
            - Header: Expect-CT
              Value: max-age=7776000, enforce
              Override: true
            - Header: Permissions-Policy
              Value:
                accelerometer=(),
                ambient-light-sensor=(),
                autoplay=(),
                battery=(),
                camera=(),
                cross-origin-isolated=(),
                display-capture=(),
                document-domain=(),
                encrypted-media=(),
                execution-while-not-rendered=(),
                execution-while-out-of-viewport=(),
                fullscreen=(),
                geolocation=(),
                gyroscope=(),
                keyboard-map=(),
                magnetometer=(),
                microphone=(),
                midi=(),
                navigation-override=(),
                payment=(),
                picture-in-picture=(),
                publickey-credentials-get=(),
                screen-wake-lock=(),
                sync-xhr=(),
                usb=(),
                web-share=(),
                xr-spatial-tracking=(),
                clipboard-read=(),
                clipboard-write=(),
                gamepad=(),
                speaker-selection=(),
                conversion-measurement=(),
                focus-without-user-activation=(),
                hid=(),
                idle-detection=(),
                interest-cohort=(),
                serial=(),
                sync-script=(),
                trust-token-redemption=(),
                window-placement=(),
                vertical-scroll=()
              Override: true

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref Name
        Enabled: true
        HttpVersion: http2
        PriceClass: !Ref CloudFrontPriceClass
        Origins:
          - S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
            DomainName: !Ref BucketRegionalFqdn
            Id: !Sub S3-${BucketName}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub S3-${BucketName}
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          # CachingOptimized managed cache policy
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          # UserAgentRefererHeaders managed origin request policy
          OriginRequestPolicyId: acba4595-bd28-49b8-b9fe-13317c0390fa
          ResponseHeadersPolicyId: !Ref SecurityHeaders
          Compress: true
        Aliases: [ !Ref FullyQualifiedDomainName ]
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
          AcmCertificateArn: !Ref CertificateArn


Outputs:
  DistributionId:
    Value: !Ref Distribution

  DistributionFqdn:
    Value: !GetAtt Distribution.DomainName
